#ifndef ACCEL_CONSTANTS_H
#define ACCEL_CONSTANTS_H

#define ACCEL_CTRL_REG2_SOFT_RESET 0x80
#define ACCEL_RESET_DELAY_MS 50
#define ACCEL_SIGN_BIT_14 0x2000
#define ACCEL_SIGN_EXTEND_14 0xC000

#endif // ACCEL_CONSTANTS_H
